# Generated by Django 4.2.4 on 2024-07-01 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="I90Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("a_number", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "usci_number",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "family_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("given_name", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "name_change_yes",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "name_change_no",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "name_change_na",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "name_change_family_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "name_change_first_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "name_change_middle_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "mailing_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "street_name_number",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("apt", models.BooleanField(blank=True, default=False, null=True)),
                ("ste", models.BooleanField(blank=True, default=False, null=True)),
                ("flr", models.BooleanField(blank=True, default=False, null=True)),
                ("city_town", models.CharField(blank=True, max_length=250, null=True)),
                ("state", models.CharField(blank=True, max_length=250, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=250, null=True)),
                ("province", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("country", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "physical_street_name_number",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "physical_apt",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "physical_ste",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "physical_flr",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "physical_city_town",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "physical_state",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "physical_zip_code",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "physical_province",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "physical_postal_code",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "physical_country",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "gender_male",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "gender_female",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("dob", models.DateField(blank=True, null=True)),
                (
                    "birth_city_town",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "birth_country",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "mother_first_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "father_first_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "class_of_admission",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("date_of_admission", models.DateField(blank=True, null=True)),
                ("ssn", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "lawful_permanent_resident",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "conditional_permanent_resident",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "previous_card_lost",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "previous_card_never_received",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "existing_card_mutilated",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "existing_card_incorrect_data_DHS",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "biographic_information_legally_changed",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "existing_card_expired",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "my_14_birthday_registering_after",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "my_14_birthday_registering_before",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "permanent_resident",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "port_of_entry",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("commuter", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "convertered_to_lawful_permanent_resident",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "prior_edition_alien_registration_card",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "previous_card_lost_B",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "previous_card_never_received_B",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "existing_card_mutilated_B",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "existing_card_incorrect_data_DHS_B",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "biographic_information_legally_changed_B",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "immigrant_visa_adjustment_location",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "immigrant_visa_issued_location",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "us_destination_at_admission",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "port_of_entry_2",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "ever_exclusion_deportation_removal_proceedings_yes",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "ever_exclusion_deportation_removal_proceedings_no",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "ever_filed_form_abandonment_by_alien_of_status_yes",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "ever_filed_form_abandonment_by_alien_of_status_no",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "ethnicity_hispanic_latino",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "ethnicity_not_hispanic_latino",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "ethnicity_white",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "ethnicity_asian",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "ethnicity_black",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "ethnicity_american_indian",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "ethnicity_native_hawaiian",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "height_feet",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "height_inch",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("weight", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "eye_color_black",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "eye_color_blue",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "eye_color_brown",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "eye_color_gray",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "eye_color_green",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "eye_color_hazel",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "eye_color_maroon",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "eye_color_pink",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "eye_color_unknown",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "hair_color_bald",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "hair_color_black",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "hair_color_blond",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "hair_color_brown",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "hair_color_gray",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "hair_color_red",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "hair_color_sandy",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "hair_color_white",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "hair_color_unknown",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "accommodation_because_disabilities",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("deaf", models.BooleanField(blank=True, default=False, null=True)),
                ("deaf_more", models.TextField(blank=True, null=True)),
                ("blind", models.BooleanField(blank=True, default=False, null=True)),
                ("blind_more", models.TextField(blank=True, null=True)),
                ("other", models.BooleanField(blank=True, default=False, null=True)),
                ("other_more", models.TextField(blank=True, null=True)),
                (
                    "applicant_able_understand_english",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "applicant_request_interpreter",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "interpreter_read_language",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "my_request",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "my_request_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "applicant_contact_phone_number",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "applicant_contact_mobile_number",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "applicant_contact_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "applicant_signature",
                    models.ImageField(blank=True, null=True, upload_to="signatures/"),
                ),
                ("applicant_signature_date", models.DateField(blank=True, null=True)),
                (
                    "interpreter_first_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "interpreter_last_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "interpreter_business_organization",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "interpreter_street_number_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "interpreter_apt",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "interpreter_ste",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "interpreter_flr",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "interpreter_city_town",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "interpreter_state",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "interpreter_zip_code",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "interpreter_province",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "interpreter_postal_code",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "interpreter_country",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "interpreter_phone_number",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "interpreter_mobile_number",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "interpreter_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "other_language",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "interpreter_signature",
                    models.ImageField(blank=True, null=True, upload_to="signatures/"),
                ),
                ("interpreter_signature_date", models.DateField(blank=True, null=True)),
                (
                    "preparer_last_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "preparer_first_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "preparer_business_organization",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "preparer_street_number_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "preparer_apt",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "preparer_ste",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "preparer_flr",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "preparer_city_town",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "preparer_state",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "preparer_zip_code",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "preparer_province",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "preparer_postal_code",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "preparer_country",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "preparer_phone_number",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "preparer_mobile_number",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "preparer_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "preparer_signature",
                    models.ImageField(blank=True, null=True, upload_to="signatures/"),
                ),
                ("preparer_signature_date", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
