# Generated by Django 4.2.4 on 2024-07-01 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="i90application",
            name="an_attorney",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="i90application",
            name="an_attorney_extends",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="i90application",
            name="an_attorney_not_extends",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="i90application",
            name="not_an_attorney",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="i90application",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="filled_pdfs/"),
        ),
    ]
