# Generated by Django 5.0.6 on 2024-06-01 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="fcm_token",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="image",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="phone_number",
        ),
    ]
